<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);SKEXP0001;SKEXP0020</NoWarn>
    <UserSecretsId>dotnet-DbSentinel.Collector-8b0b2d41-250e-44c2-a95a-3024fe4531e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Milvus" Version="1.70.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.70.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.69.0-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DbSentinel.Parser\DbSentinel.Parser.csproj" />
  </ItemGroup>
</Project>
